---
- name: Backup mysql databases
  docker_container:
    env:
      MULTI_FILES: "{{ mysql_backup_multifiles }}"
      MYSQLDUMP_DATABASE: "{{ mysql_backup_databases }}"
      MYSQLDUMP_OPTIONS: "{{ mysql_backup_dump_options }}"
      MYSQL_HOST: "{{ mysql_backup_host }}"
      MYSQL_PASSWORD: "{{ mysql_backup_password }}"
      MYSQL_PORT: "{{ mysql_backup_port }}"
      MYSQL_USER: "{{ mysql_backup_user }}"
      S3_ACCESS_KEY_ID: "{{ mysql_backup_s3_access_key_id }}"
      S3_BUCKET: "{{ mysql_backup_s3_bucket }}"
      S3_PREFIX: "{{ mysql_backup_s3_prefix }}"
      S3_REGION: "{{ mysql_backup_s3_region }}"
      S3_SECRET_ACCESS_KEY: "{{ mysql_backup_s3_secret_access_key }}"
      SCHEDULE: "{{ mysql_backup_schedule }}"
    image: schickling/mysql-backup-s3
    name: mysql-backup
    networks:
      - name: "{{ mysql_backup_network }}"
    pull: true
    state: started
